import EEObject from "grimoirejs/ref/Base/EEObject";
import Component from "grimoirejs/ref/Node/Component";
/**
 * Provides managing all promise on initializing resources.
 */
declare class AssetLoader extends EEObject {
    /**
     * Promise count registered.
     * @type {number}
     */
    registerCount: number;
    /**
     * Promise count finished successfully.
     * @type {number}
     */
    loadCount: number;
    /**
     * Promise count completed(success and errored)
     * @type {number}
     */
    completeCount: number;
    /**
     * Promise count errored
     * @type {number}
     */
    errorCount: number;
    /**
     * Main promise to provide tasks for waiting for all resource loading.
     * @type {Promise<void>}
     */
    promise: Promise<void>;
    /**
     * For memorize resolve function generated by main promise.
     * @type {[type]}
     */
    private _resolve;
    /**
     * Register an promise to be waited until finished.
     */
    register<T>(promise: Promise<T>, component: Component): Promise<T>;
    /**
     * Verify all promises are completed.
     */
    private _checkLoadCompleted();
}
export default AssetLoader;
